apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8002  # Port for external access
      targetPort: 8002  # Port on the container
  type: ClusterIP  # Internal access within the cluster
