apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: mercysakah/order_service:1.0  # Replace with your Docker Hub image name and tag
        ports:
        - containerPort: 8000  # The port exposed by the container
