apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8000  # Port for external access
      targetPort: 8000  # Port on the container
  type: ClusterIP  # Internal access within the cluster
