apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8001  # Port for external access
      targetPort: 8001  # Port on the container
  type: ClusterIP  # Internal access within the cluster
